/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Abdur Razzak Sawon (https://sketchfab.com/md.abdur.razzak.sawon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brushed-antique-bronze-3a8169852b2e49f6818fbd688d331c07
Title: Brushed_Antique_Bronze
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function Frame({onClick}) {
  const { nodes, materials } = useGLTF('../src/assets/models/brushed_antique_bronze.glb')
  const [hover, sethover] = useState(false)

  useEffect(() => {
    document.body.style.cursor = hover ? "pointer" : "grab";
  }, [hover])

  return (
    <group 
      dispose={null} 
      position={[0, 4, -4.8]} 
      scale={2} 
      onClick={onClick}
      onPointerOver={() => {
        sethover(true)
      }}
      onPointerOut={() => {
        sethover(false)
      }}
    >
      <group rotation={[-Math.PI, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes.BrushedAntiqueBronzeWallPictureFrame_BrushedAntiqueBronzeWallPictureFrame_0
              .geometry
          }
          material={materials.BrushedAntiqueBronzeWallPictureFrame}
          rotation={[-Math.PI, 0, 0]}
          scale={0.001}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../src/assets/models/brushed_antique_bronze.glb')