/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mehdi Shahsavan (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chairmans-chair--20mb-02152d9f5083418399fbb5f64b129bf6
Title: Chairman's Chair_ 20MB
*/
import * as THREE from 'three'
import { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import gsap from "gsap"


export function Chair(props) {
  const { nodes, materials } = useGLTF('./models/chairmans_chair__20mb.glb')
  const chairRef = useRef();
  const camera = useThree((state) => state.camera);
  const tl = useRef();
  const scroll = useScroll();

  const lookAtPoint = new THREE.Vector3(-0.8, 0.01, -0.8)
  

  useFrame(() => {
    tl.current.seek(scroll.offset * tl.current.duration())
    camera.lookAt(lookAtPoint)
  })

  useLayoutEffect(() => {
    tl.current = gsap.timeline();

    tl.current.from(
        chairRef.current.rotation,
        {
            duration: 0.25,
            y: Math.PI*1.2,
        },
        0
    );

    tl.current.to(
        chairRef.current.position,
        {
            duration: 0.25,
            x: -1, 
            z: 1
        },
        0
    )

    tl.current.to(
      camera.position,
      {
        duration: 0.25,
        x:0.4,
        y:1,
        z:0.4
      },
      0.5
    )

  }, []);
  
  return (
    <group 
        {...props} 
        dispose={null}
        ref={chairRef} 
        scale={0.01}
        rotation={[0, 0.8, 0]}
        position={[0, -1, 0]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Remesh__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-1.784, 82.552, -2.642]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.scene__0.geometry}
        material={materials['Scene_-_Root']}
        position={[1.784, 17.212, 2.642]}
      />
    </group>
  )
}

useGLTF.preload('./models/chairmans_chair__20mb.glb')
