/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: felixawani (https://sketchfab.com/felixawani)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-05353724b7884bfb81211c7033a57fd4
Title: Computer Desk
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
    const deskRef = useRef();
    const { scene } = useGLTF('./models/computer_desk.glb')

    return (
        <mesh 
            castShadow
            receiveShadow
            {...props} 
            ref={deskRef}
            scale={0.4}
            position={[-0.8, 0, -0.8]}
            rotation={[0, 0.8, 0]}
        >
            <primitive object={scene} />
        </mesh>
    )
}

useGLTF.preload('./models/computer_desk.glb')
