/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CoderBoy (https://sketchfab.com/baso4388)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/screen-3cee090622f5474a810d40be6892c97d
Title: screen
*/

import { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import gsap from "gsap"

export function Screen(props) {
    const screenRef = useRef();
    const { scene } = useGLTF('./models/screen.glb')
    const tl = useRef();
    const scroll = useScroll();

    useFrame(() => {
        tl.current.seek(scroll.offset * tl.current.duration())
    })

    useLayoutEffect(() => {
        tl.current = gsap.timeline();

        tl.current.to(
            screenRef.current.scale,
            {
                duration: 0.5, 
                x: 0.4,
                y: 0.4, 
                z: 0.4
            },
            0.5
        )
    })

    return (
        <mesh 
            castShadow
            receiveShadow
            {...props} 
            ref={screenRef}
            scale={0.25}
            position={[-0.8, 0.005, -0.8]}
            rotation={[0, 0.8, 0]}
        >
            <primitive object={scene} />
        </mesh>
    )
}

useGLTF.preload('./models/screen.glb')
